# Generated by Django 4.1.5 on 2023-03-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50, verbose_name='business name')),
                ('logo', models.ImageField(upload_to='config/', verbose_name='logo')),
                ('facebook', models.URLField(max_length=240, verbose_name='facebook')),
                ('twitter', models.URLField(max_length=240, verbose_name='twitter')),
                ('telegram', models.URLField(max_length=240, verbose_name='telegram')),
                ('pinterest', models.URLField(max_length=240, verbose_name='pinterest')),
                ('flirk', models.URLField(max_length=240, verbose_name='flirk')),
            ],
            options={
                'verbose_name': 'configuration',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('news', models.TextField(verbose_name='news')),
            ],
            options={
                'verbose_name': 'new',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptors',
            },
        ),
    ]
