# Generated by Django 3.2.18 on 2023-07-08 19:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de negocio')),
                ('business_name_active', models.BooleanField(default=False, verbose_name='Nombre de negocio activo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo')),
                ('facebook', models.URLField(blank=True, max_length=240, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, max_length=240, null=True, verbose_name='twitter')),
                ('telegram', models.URLField(blank=True, max_length=240, null=True, verbose_name='telegram')),
                ('pinterest', models.URLField(blank=True, max_length=240, null=True, verbose_name='pinterest')),
                ('flirk', models.URLField(blank=True, max_length=240, null=True, verbose_name='flirk')),
                ('suscribe_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo suscripción')),
                ('suscribe_text', models.TextField(blank=True, null=True, verbose_name='Texto suscripción')),
            ],
            options={
                'verbose_name': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('news', ckeditor.fields.RichTextField(verbose_name='Noticias')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.TextField(max_length=160, verbose_name='sms')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMSs',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Subscriptor',
                'verbose_name_plural': 'Subscriptores',
            },
        ),
        migrations.CreateModel(
            name='UrlImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/imagenes', verbose_name='imagen')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.new')),
            ],
        ),
    ]
