# Generated by Django 4.1.5 on 2023-03-11 23:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='news',
            field=ckeditor.fields.RichTextField(verbose_name='news'),
        ),
    ]
