# Generated by Django 4.1.5 on 2023-07-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlImg',
            new_name='EmailImg',
        ),
    ]
