# Generated by Django 4.1.5 on 2023-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_urlimg_emailimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='responder_a',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
