# Generated by Django 4.1.5 on 2023-03-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_config_business_name_alter_config_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='suscribe_text',
            field=models.TextField(blank=True, null=True, verbose_name='suscribe text'),
        ),
        migrations.AddField(
            model_name='config',
            name='suscribe_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='suscribe title'),
        ),
    ]
