# Generated by Django 4.1.5 on 2023-03-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_config_suscribe_text_config_suscribe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='business_name_active',
            field=models.BooleanField(default=False, verbose_name='business name in title'),
        ),
    ]
