# Generated by Django 4.1.5 on 2023-05-25 05:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_config_business_name_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Configuración'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='suscriptor',
            options={'verbose_name': 'Subscriptor', 'verbose_name_plural': 'Subscriptores'},
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='config',
            name='business_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de negocio'),
        ),
        migrations.AlterField(
            model_name='config',
            name='business_name_active',
            field=models.BooleanField(default=False, verbose_name='Nombre de negocio activo'),
        ),
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='config',
            name='suscribe_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto suscripción'),
        ),
        migrations.AlterField(
            model_name='config',
            name='suscribe_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo suscripción'),
        ),
        migrations.AlterField(
            model_name='new',
            name='news',
            field=ckeditor.fields.RichTextField(verbose_name='Noticias'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
