# Generated by Django 4.1.5 on 2023-05-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_config_options_alter_new_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.TextField(verbose_name='sms')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMSs',
            },
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono'),
        ),
    ]
