# Generated by Django 3.2.18 on 2023-07-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_sms_alter_suscriptor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sms',
            field=models.TextField(max_length=160, verbose_name='sms'),
        ),
    ]
